FizzBuzz/FizzBuzz/Models/FizzBuzzModel.cs
namespace FizzBuzz.Models
{
    using PagedList;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class FizzBuzzModel
    {

        [Required(ErrorMessage = "Please Enter a Number")]
        [Range(1, 1000, ErrorMessage = "Please Enter a Number between 1 and 1000")]
        [Display(Name = "User Input")]
        public int? InputNumber { get; set; }

        public IPagedList<string> numbers { get; set; }
    }
}

FizzBuzz/FizzBuzz/Controllers/FizzBuzzController.cs
namespace FizzBuzz.Controllers
{
    using System;
    using System.Web.Mvc;
    using FizzBuzz.Models;
    using FizzBuzzRules.Interfaces;
    using PagedList;

    public class FizzBuzzController : Controller
    {
        private readonly IFizzBuzzRepository FizzBuzzRepository;
        private readonly int pageSize = 20;
        private int pageNumber;
        public FizzBuzzController(IFizzBuzzRepository FizzBuzzRepository)
        {
            this.FizzBuzzRepository = FizzBuzzRepository;
        }

        [HttpGet]
        public ActionResult Index(string inputNumber, int? page)
        {
            var model = new FizzBuzzModel();

            if (!string.IsNullOrEmpty(inputNumber))
            {
                int number = Convert.ToInt32(inputNumber);
                model = this.GetFizzBuzzResult(number, page);
                return View("Index", model);
            }

            return View("Index", model);
        }

        [HttpPost]
        public ActionResult Index(FizzBuzzModel model, int? page)
        {
            var fizzbuzzModel = new FizzBuzzModel();
            if (ModelState.IsValid)
            {
                int number = Convert.ToInt32(model.InputNumber);
                fizzbuzzModel = this.GetFizzBuzzResult(number, page);
                return View("Index", fizzbuzzModel);
            }
            return View("Index", fizzbuzzModel);
        }

        private FizzBuzzModel GetFizzBuzzResult(int userInput, int? page)
        {
            pageNumber = page.HasValue ? page.Value : 1;

            var result = this.FizzBuzzRepository.GetResults(userInput);
            var model = new Models.FizzBuzzModel
            {
                InputNumber = userInput,
                numbers = (PagedList<string>)result.ToPagedList(pageNumber, pageSize)
            };
            return model;
        }
    }
}

FizzBuzz/FizzBuzz/Views/FizzBuzz/Index.cshtml
@model FizzBuzz.Models.FizzBuzzModel
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm("Index", "FizzBuzz", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Print Numbers</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.InputNumber, "Enter a number", htmlAttributes: new { @class = "control-label col-md-2", Style = "color:red" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.InputNumber, new { htmlAttributes = new { @class = "form-control" } })
                <div class="col-md-10">
                    @Html.ValidationMessageFor(model => model.InputNumber)
                </div>
            </div>
        </div>
        <div class="from-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="SUBMIT" class="btn btn-default" />
            </div>
        </div>
        <div class="form-group">
            @if (Model?.numbers?.Count > 0)
            {
                <div class="col-md-offset-2 col-md-10">
                    @foreach (var item in Model.numbers)
                    {
                        var result = item.Split(' ');
                        foreach (var str in result)
                        {
                            <span class="@str">@str</span>
                        }
                        <br />

                    }
                </div>
                <div id="container" style="margin-left: 20px">

                    @{ var renderOptions = PagedListRenderOptions.Minimal;
                        renderOptions.LinkToPreviousPageFormat = "Previous";
                        renderOptions.LinkToNextPageFormat = "Next"; }

                    <div class="pagination" style="margin-left: 400px">
                        @Html.PagedListPager(Model.numbers, page => Url.Action("Index", new { Model.InputNumber, page }), renderOptions)
                    </div>

                </div>
            }
        </div>
    </div>
}

FizzBuzz/FizzBuzz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - FizzBuzz Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            
           
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - FizzBuzz Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>